### PR TITLE
Fixing getCredentials crash for user that contains less fields

### LINKED ISSUE #20: Login without a region.
The API has the option to log in without specifying a region.
Let's add support for that as it will make the login process more straightforward.

### LINKED ISSUE #22: Get outlets name
Currently when calling `getDevice()` or `getDevices();` the params contains all switches with only switch state and outlet number.

We are missing the switch name

### PR DESCRIPTION
**Pull request by guyluz11**
A pr to the new branch (that is currently in a pr), that adds for it a fix for `getCredentials` crushing for my user

Fix #20 

Fix #22

### CODE REVIEW

**Comment by ianmaciel** [comment]
I'm sorry @guyluz11 . I've been busy on the last days. I'll try to get back here and not let these PR blocked here.

**Comment by guyluz11** [comment]
> I'm sorry @guyluz11 . I've been busy on the last days. I'll try to get back here and not let these PR blocked here.

Thanks 🙏

**Review by ianmaciel — APPROVED** [review]

**Comment by guyluz11** [comment]
This is your repo, I can't Marge pr even if I wanted to.

Please Marge it for me 

Thanks

**Comment by ianmaciel** [comment]
LOL
Sure!

Ps. It was late, and I wasn't on my machine so I didn't want to make any real action.

BTW:  it might be a good idea to move this repo to a different space where you can update without depending on me. I don't want to be a blocker and at the same time I'd rather have a unique project being updated and maintained than have my own outdated.

Or.. I could just turn a maintainer here..

**Comment by ianmaciel** [comment]
BTW... I still need to work on my PR

**Pull request merged**
